/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import("ant-design-vue/es")["App"]
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ARadioButton: typeof import("ant-design-vue/es")["RadioButton"]
    ARadioGroup: typeof import("ant-design-vue/es")["RadioGroup"]
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
  }
}
